name: CLA
on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          path-to-signatures: signatures/cla.json
          path-to-document: https://github.com/uips-browser-kit/.github/blob/main/CLA.md
          branch: cla-signatures
          allowlist: bot*,dependabot[bot]
